### ISSUE TITLE
By passing the default limit of 100

### ISSUE THREAD

**Issue by KaushikR** [cjw296/python-workfront#2]
Hi Chris,

When I try to get tasks using the 

`session.search(api.Task) `

command, it seems to fetch only the first 100 results. I took a look at the [WorkFront API doc](https://developers.workfront.com/api-docs/#Limits) and they seem to mention a '$$LIMIT' param to increase the number of results fetched. Is there some way to plug this in the search command instead of using a low-level GET request ?

Thanks,
Kaushik 

P.S- I am very very new to Py so please bear with me if this question is too trivial! Thanks for the wonderful API.

**Comment by cjw296** [comment]
Try:

```python
session.search(api.Task, **{'$$LIMIT', 1000})
```

...or whatever you require.

**Comment by KaushikR** [comment]
In case any one else has the same question, the correct command is 

`session.search(api.Task, **{'$$LIMIT': 1000})`

**Comment by cjw296** [comment]
You mean, exactly what I wrote? ;-)

**Comment by KaushikR** [comment]
Well, there is a subtle difference. 

Its a **':'** instead of a **','**. 

If you use the **','**, it throws this warning : 

`TypeError:` search() argument after ** must be a mapping, not set

**Comment by cjw296** [comment]
Ah, good spot, I've corrected my comment above.
